#!/bin/bash
apt update && apt upgrade
pkg install php
pkg install wget
pkg install python
pkg install python2
gem install lolcat
pkg install openssh
pkg install ssh
pkg install curl
pkg install toilet


toilet -f mono12  Done !!! | lolcat
echo
echo -e "\e[1m Now Run bash sparkz...!!!"
echo
echo -e "\e[1m\e[32m Developed by :\e[33m sparkz-technology (sparkz)"
