#!/bin/bash
apt update 
pkg install php
pkg install wget

toilet -f mono12  Done! | lolcat
echo
echo -e "\e[1m Now Run sparkz...!!!"
echo
echo -e "\e[1m\e[32m Developed by :\e[33m sparkz-technology (sparkz)"
clear
cd 
cd sparkz
bash sparkz
