#!/bin/bash
apt update 
gem install lolcat
apt upgrade


toilet -f mono12  Done! | lolcat
echo
echo -e "\e[1m Now Run bash sparkz...!!!"
echo
echo -e "\e[1m\e[32m Developed by :\e[33m sparkz-technology (sparkz)"
cd 
cd sparkz
bash sparkz
