#!/bin/bash
apt update
pkg install php
pkg install wget
pkg install python
pkg install python2
pip install lolcat
pkg install openssh
pkg install ssh
pkg install cure
pkg install toilet


figlet -f big Done !!! | lolcat
echo
echo -e "\e[1m Now Run bash sparkz...!!!"
echo
echo -e "\e[1m\e[32m Developed by :\e[33m sparkz-technology (sparkz)"
